### ISSUE TITLE
[FEATURE] feed groups/categories

### ISSUE THREAD

**Issue by toastal** [ckampfe/russ#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I would like to be able to group feeds into categories like:

* Podcasts
* Blogs
* Code releases
* Personal project issues

etc. Currently there's no hierarchy so it's difficulty to tell understand what the feed is at a glance or the priority (where issues on personal projects are more important to attend to vs. a podcast release). This seems simple on the surface, but would involve needing a new management system to move feeds to and from group to other groups, adding+deleting groups.

**Comment by ckampfe** [comment]
Hello @toastal , thank you for the suggestion. I do like the idea but do not see myself having the time to build such a feature, as a sole maintainer. For now, short of a pull request demonstrating otherwise, this is not currently something I see being worth its complexity. Thank you!
