### ISSUE TITLE
[FEATURE] Change a couple of commands more similar to Vim

### ISSUE THREAD

**Issue by victorhck** [ckampfe/russ#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hello
I think that this couple of commands should be changed to align to Vim commands.

x - refresh all feeds
c - copy the selected link to the clipboard (feed or entry)

x in Vim delete the character under the cursor, so maybe should be replaced with R (for example) to refresh
and in Vim y is used to _yank_ aka copy, so maybe c should be replaced with y

just a suggestion.
Thanks for your work.

**Comment by ckampfe** [comment]
Hi @victorhck , thank you for the suggestion! At this time, perfect vim compatibility is not a project goal. Some things are like vim, some are not, and this is just the reality of the project right now. So, I probably won't be accepting changes of this nature so as to not break existing users.

In the future it might make sense to build a config system that allows the user to select their own keybindings, colors, layout, etc., but this is not something I am working on at the moment as it can get very complicated and time consuming. If you have ideas regarding a configuration system or any other improvements, I welcome them! Thank you.
