### ISSUE TITLE
[BUG] Unable to get title for entry id *

### ISSUE THREAD

**Issue by Cavernosa** [ckampfe/russ#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

{"label"=>"Linux"}

### Current Behavior

When opening Mastodon feeds, this crash occurs:
```
thread 'main' panicked at 'Unable to get title for entry id [random number]', src/ui.rs:339:17
stack backtrace:
0: rust_begin_unwind at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
1: core::panicking::panic_fmt at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
2: russ::ui::draw
3: russ::main
```

### Steps To Reproduce

1. Add a feed from any Mastodon user with at least one post (e.g. `https://mastodon.social/@Gargron.rss`)
2. Navigate to the respective feed

### Anything else?

Does not crash if the user never posted anything, or if the feed was hidden via the `a` key

**Comment by ckampfe** [comment]
Hi @Cavernosa thank you for the bug report. I think this is due to a quick hack I put in for the case where an entry doesn't have a title in the actual Atom/RSS. I don't know of a great way to handle this general other than defaulting to a placeholder title, so that's what I'm going to do. Look for a commit for that shortly.

**Comment by ckampfe** [comment]
Hm actually I think what I will do is to show a short, maybe 30-character preview of the content.

**Comment by ckampfe** [comment]
Eh on second thought, showing a preview is significantly more complication. Maybe I will get to it at some point but for now I will get this to stop crashing.

**Comment by ckampfe** [comment]
Fixed here https://github.com/ckampfe/russ/commit/e16c8022997f449b32de262252d03c2f98b80931
