### ISSUE TITLE
[BUG] a little bug on Windows10

### ISSUE THREAD

**Issue by scillidan** [ckampfe/russ#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

{"label"=>"Windows"}

### Current Behavior

I install `russ` on `Windows10` and `WSL2`.  
It runs well on `WSL`.  
But on `Windows`, I can't paste urls or make input. Any letter I type will be double.

![Snipaste_2023-06-26_20-29-26](https://github.com/ckampfe/russ/assets/19889610/9e82f725-1663-4c59-b590-1e1f632872bf)

### Anything else?

I used [DBeaver](https://dbeaver.io/) to edit the `feeds.db` file.  
Added a subscription, then update it.

![Snipaste_2023-06-26_20-38-05](https://github.com/ckampfe/russ/assets/19889610/12153cab-0ec5-4a0e-998f-064b72e545c9)

It is pleasant that it works well.

![Snipaste_2023-06-26_20-39-48](https://github.com/ckampfe/russ/assets/19889610/5a51c1c0-cbf9-4ef9-ae34-374b688b52c8)

**Comment by ckampfe** [comment]
@scillidan thank you for the bug report! Can you confirm: is this running on the host Windows or in the WSL2 VM?

I have not tried to run russ on Windows, only WSL2, but I will try to reproduce this issue as soon as possible. Thank you.

**Comment by scillidan** [comment]
Just take your time, guys :)
I run it on both Windows and WSL2.
On windows, its function should be good. Just when entering the `feed-url`, there is a bug.

**Comment by vgwidt** [comment]
I think it's because the keyup event is being picked up: https://docs.rs/crossterm/latest/crossterm/event/struct.KeyEvent.html#structfield.kind

Similar issue in ratatui example for Windows: https://github.com/ratatui-org/ratatui/pull/44/files

Adding a check for KeyEventKind::Press should fix it.

**Comment by sobharrison** [comment]
@vgwidt Yup, can confirm it picks up keyup.

@scillidan This bug impacts me on Windows for both `Mode::Normal` and `Mode::Editing`. It doubles my inputs on everything.

**Comment by ckampfe** [comment]
@scillidan Thank you again for opening this bug report. This is now fixed in https://github.com/ckampfe/russ/commit/4c3e25931f13276f0c591eac57f6ed0af95fe08f.

Thank you very much @sobharrison for contributing the fix..
