### ISSUE TITLE
[FEATURE] Scroll with Ctrl-d/Ctrl-u

### ISSUE THREAD

**Issue by Jaco-Minnaar** [ckampfe/russ#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

In vim, I like scrolling with Ctrl-u and Ctrl-d to pageUp/pageDown. I have implemented this in `russ` (it's like two lines, not a lot) and would like to do a PR, but don't want to do so without permission. Would you be interested in merging this in?

**Comment by ckampfe** [comment]
@Jaco-Minnaar yes that sounds good, go ahead and open a PR at your convenience and I will take a look. Thanks for asking!
