### ISSUE TITLE
[Feature] Ability to run without arguments

### ISSUE THREAD

**Issue by NickLarsenNZ** [ckampfe/russ#5]
I think having a default database would be a good UX improvement.

On my first time running `russ`, I expected to be able to get straight into it, but I am instead left with deciding where to put the database, and having to remember where the database is everytime I want to use it. This adds friction and would make me lose interest rather quickly.

Could the `--database-path` option become optional, with a default of say `$XDG_CONFIG_HOME/russ/database.sqlite` (eg: `$HOME/.config/russ/database.sqlite`)?

See: [XDG Base Directory spec][xdg]

[xdg]: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by ckampfe** [comment]
@NickLarsenNZ Yeah this is not a bad idea. I'll have to think about it some but I'm not opposed. I'd also welcome a PR if that's something you're interested in.

**Comment by NickLarsenNZ** [comment]
I'd be happy to raise a PR. I took a quick look at [how Alacritty looks for a config][alacritty], and thought we can do it in a similar way.

1. `$XDG_CONFIG_HOME/russ/russ.sqlite`
2. `$XDG_CONFIG_HOME/russ.sqlite`
3. `$HOME/.config/russ/russ.sqlite`
4. `$HOME/.russ.sqlite`

[alacritty]: https://github.com/alacritty/alacritty/tree/master/alacritty#configuration

**Comment by ckampfe** [comment]
> I'd be happy to raise a PR. I took a quick look at [how Alacritty looks for a config](https://github.com/alacritty/alacritty/tree/master/alacritty#configuration), and thought we can do it in a similar way.

>    $XDG_CONFIG_HOME/russ/russ.sqlite
>    $XDG_CONFIG_HOME/russ.sqlite
>    $HOME/.config/russ/russ.sqlite
>    $HOME/.russ.sqlite

Sounds good, let me know how I can help @NickLarsenNZ.

To add a bit more context: Russ' database currently only contains application state, and does not (yet?) contain any data that I consider to be "configuration". For example, the database is not intended to be edited by end users to control the Russ application itself (though it being a Sqlite database, this is certainly possible if one knows SQL).

XDG seems to have some notion of `$XDG_STATE_HOME`, but I don't know XDG well enough to know what necessarily makes sense here. In any case, changing the actual locations shouldn't be that difficult.

**Comment by NickLarsenNZ** [comment]
Oh yeah, I had used _config_ in error. XDG defines _data_ and _cache_ too. I was using _data_ in my local version, but stopped when I had to think about first run (initial creation).

**Comment by ckampfe** [comment]
Fixed by faf7dbe0c29f106db0ee84ee760115c443f5d3c4.
